name: Go

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.22]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install Dependencies
      run: go get .

    - name: Build
      run: go build -v -o hideout-${{ runner.os }} ./...
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: hideout-${{ runner.os }}
        path: hideout-${{ runner.os }}
